name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install -y cmake clang-tidy

      - name: Build
        run: BUILD_DIR=$(date +'%Y-%m-%d')_build; cmake -S . -B $BUILD_DIR && cmake --build $BUILD_DIR